import { useState } from "react";
import { Bell, CalendarClock, Check, ChevronRight, Clock3, Mail, MoreHorizontal, Plus, Send, ShieldCheck } from "lucide-react";

const tasks = [
  { title: "Serve 60-day termination notice", clause: "Clause 12 · Page 5", date: "30 JAN 2027", time: "18:30 IST", impact: "₹20,000 penalty if missed", tone: "coral", status: "PENDING" },
  { title: "Confirm renewal decision", clause: "Clause 07 · Page 4", date: "01 DEC 2026", time: "09:00 IST", impact: "Renewal window opens", tone: "amber", status: "PENDING" },
  { title: "Request deposit return", clause: "Clause 18 · Page 7", date: "01 MAR 2027", time: "10:00 IST", impact: "₹25,000 deposit recovery", tone: "lime", status: "SCHEDULED" },
];

export default function Reminders() {
  const [done, setDone] = useState<string[]>([]);
  const [showComposer, setShowComposer] = useState(false);
  return (
    <div className="page-content page-enter">
      <div className="page-header"><div><div className="eyebrow"><span className="eyebrow-line" /> DEADLINE RADAR</div><h1>Stay ahead of <span className="lime-dot">the clock.</span></h1><p>Every obligation gets the right reminder, at the right moment.</p></div><button className="lime-button" onClick={() => setShowComposer(true)}><Plus size={16} /> Add reminder</button></div>
      <div className="reminder-overview"><div className="reminder-hero-stat"><span className="summary-label">NEXT DEADLINE</span><strong>146 <small>days</small></strong><p>Serve termination notice</p><span className="reminder-date">30 January 2027 · 18:30 IST</span></div><div className="reminder-mini-stats"><div><CalendarClock size={17} /><span>03</span><small>Active tasks</small></div><div><Send size={17} /><span>09</span><small>Emails scheduled</small></div><div><Check size={17} /><span>04</span><small>Completed</small></div></div></div>
      <div className="reminder-layout"><section className="panel task-panel"><div className="panel-heading"><div><span className="section-kicker">UPCOMING OBLIGATIONS</span><h2>Task timeline</h2></div><button className="panel-menu"><MoreHorizontal size={18} /></button></div><div className="task-list">{tasks.map((task) => { const completed = done.includes(task.title); return <div className={`task-card ${completed ? "completed" : ""}`} key={task.title}><div className={`task-marker ${task.tone}`} /> <div className="task-main"><div className="task-date-row"><span>{task.date} · {task.time}</span><span className={`task-status ${completed ? "complete" : task.status.toLowerCase()}`}>{completed ? "COMPLETED" : task.status}</span></div><h3>{task.title}</h3><p>{task.clause}</p><div className="task-impact"><span>Financial impact</span><strong>{task.impact}</strong></div></div><button className={`task-check ${completed ? "done" : ""}`} onClick={() => setDone((current) => completed ? current.filter((item) => item !== task.title) : [...current, task.title])}>{completed ? <Check size={15} /> : <span />}</button></div>})}</div></section><aside className="panel schedule-panel"><div className="section-kicker">NOTIFICATION ENGINE</div><h2>Every deadline, covered.</h2><p className="schedule-copy">LegalLens will keep watch and dispatch a clear, actionable email without storing your source file.</p><div className="schedule-steps"><div><span>T − 72H</span><strong>3 days before</strong><small>Preparation reminder</small></div><div><span>T − 24H</span><strong>1 day before</strong><small>Decision reminder</small></div><div><span>T − 05H</span><strong>5 hours before</strong><small>Final nudge</small></div></div><div className="email-card"><div className="email-icon"><Mail size={17} /></div><div><strong>om.mehta@example.com</strong><span>Verified delivery address</span></div><Check size={15} className="email-check" /></div><div className="schedule-privacy"><ShieldCheck size={14} /> HMAC-secured one-click actions</div></aside></div>
      {showComposer && <div className="modal-backdrop" onClick={() => setShowComposer(false)}><div className="upload-modal reminder-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setShowComposer(false)}>×</button><div className="modal-eyebrow"><Bell size={14} /> Custom reminder</div><h2>Set a new contract nudge.</h2><p>Connect a deadline to a clause and LegalLens will schedule the reminder sequence.</p><label className="form-label">Task title<input placeholder="e.g. Request written renewal confirmation" /></label><label className="form-label">Deadline<input type="datetime-local" /></label><div className="modal-footer"><span><Clock3 size={14} /> 3-stage sequence enabled</span><button className="lime-button" onClick={() => setShowComposer(false)}>Create reminder</button></div></div></div>}
    </div>
  );
}
